### PR TITLE
fix: get registerurl from util

### PR DESCRIPTION
**Pull request by lxm**
Signed-off-by: lxm <lxm.xupt@gmail.com>

### CODE REVIEW

**Comment by lxm** [comment]
these changes had been already merged before. but i found that the code has been  reverted by someone. 
I want to know why

**Comment by haord** [comment]
The code is not restored,  these changes are to add vpc mode to hybrid vm.

**Comment by haord** [comment]
https://github.com/aliyun/aliyun_assist_client/blob/release/agent/hybrid/hybrid.go#L49

Note that this function 'Register' adds a new parameter 'networkmode', domain names are different under different network modes.

**Comment by lxm** [comment]
> https://github.com/aliyun/aliyun_assist_client/blob/release/agent/hybrid/hybrid.go#L49
> 
> Note that this function 'Register' adds a new parameter 'networkmode', domain names are different under different network modes.

so i changed the code to support get vpc host by `GetVpcServerHost` so that we can handle self-hosted server host.

**Comment by haord** [comment]
Thanks for this contribution, we plan to incorporate part of this in a future release

**Comment by lxm** [comment]
Any futher information?  I saw a new version has been released, what should be done before this PR can be merged

**Comment by haord** [comment]
The changes in this pr are related to our upcoming new features, so these changes will be applied when the new features are released. Until then this PR will remain open.

**Comment by lxm** [comment]
Two versions have been released after this pr created. I'm confused about the definition of the new version. Can you explain some detailed rules about community PR here.

**Comment by lxm** [comment]
> Thanks for this contribution, we plan to incorporate part of this in a future release

closed?

**Pull request closed without merging**
